---
- name: Manage Windows Update Service
  hosts: all
  tasks:
    - name: Ensure Windows Update service is running and set to automatic
      win_dsc:
        resource_name: Service
        Name: wuauserv
        State: Running
        StartUpType: Automatic