---
- name: Setup DSC on Windows 10 VM
  hosts: all
  gather_facts: no
  tasks:
    - name: All tasks
      block:
        - name: Configure the Local Configuration Manager (LCM)
          win_shell: |
            [DSCLocalConfigurationManager()]
            configuration LCMConfig {
                Node localhost {
                    Settings {
                        ConfigurationMode = 'ApplyAndMonitor'
                        RebootNodeIfNeeded = $true
                        RefreshMode = 'Push'
                    }
                }
            }
            LCMConfig -OutputPath "C:\DSC\LCM"
            Set-DscLocalConfigurationManager -Path "C:\DSC\LCM"

        - name: Create and apply DSC configuration to set the time zone
          win_shell: |
            Configuration TimeZoneConfig {
                Import-DscResource -ModuleName xTimeZone

                Node 'localhost' {
                    xTimeZone TimeZone {
                        IsSingleInstance = 'Yes'
                        TimeZone = 'Pacific Standard Time'
                    }
                }
            }
            TimeZoneConfig -OutputPath "C:\DSC\TimeZone"
            Start-DscConfiguration -Path "C:\DSC\TimeZone" -Wait -Verbose

        - name: Verify the time zone
          win_shell: Get-TimeZone
          register: timezone_result

        - name: Display time zone result
          debug:
            var: timezone_result.stdout_lines

      rescue:
        - name: Handle any errors in the block
          debug:
            msg: "An error occurred, but we're continuing."

        # Optionally, you can add more tasks to handle errors
        - name: Log error details
          debug:
            var: ansible_failed_task

