---
- name: Manage Windows Update Service
  hosts: windows
  tasks:
    - name: Ensure Windows Update service is running and set to automatic
      community.windows.win_dsc:
        resource_name: Service
        Name: wuauserv
        State: Running
        StartUpType: Automatic